# Generated by Django 4.1.5 on 2023-01-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Адрес")),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="Долгота"
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=8, verbose_name="Широта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(max_length=30, null=True, verbose_name="Фамилия"),
                ),
                (
                    "username",
                    models.CharField(max_length=30, unique=True, verbose_name="Логин"),
                ),
                ("password", models.CharField(max_length=30, verbose_name="Пароль")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Пользователь", "USER"),
                            ("Администратор", "ADMIN"),
                            ("Модератор", "MODERATOR"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="Должность",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Возраст")),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
