# Generated by Django 4.1.5 on 2023-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location_pk",
            field=models.ManyToManyField(to="users.location", verbose_name="Адрес"),
        ),
    ]
