# Generated by Django 4.1.5 on 2023-01-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_location_pk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location_pk",
            new_name="location_id",
        ),
    ]
