# Generated by Django 4.1.5 on 2023-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "Пользователь"),
                    ("ADMIN", "Администратор"),
                    ("MODERATOR", "Модератор"),
                ],
                default="User",
                max_length=20,
                verbose_name="Должность",
            ),
        ),
    ]
