# Generated by Django 4.1.5 on 2023-01-26 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_location_pk_user_location_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="location_id",
            new_name="location",
        ),
    ]
