# Generated by Django 4.1.5 on 2023-01-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("User", "Пользователь"),
                    ("Admin", "Администратор"),
                    ("Moderator", "Модератор"),
                ],
                default="User",
                max_length=20,
                verbose_name="Должность",
            ),
        ),
    ]
